media:
  - name: experienceMedia
    input: ExperienceMedia
    output: ExperienceMedia
  - name: projectMedia
    input: ProjectMedia
    output: ProjectMedia
content:
  - name: posts
    label: Posts
    path: ProjectPosts
    type: collection
    fields:
      - { name: title, label: Title, type: string }
      - { name: layout, type: string, hidden: true, default: post }
      - { name: description, label: Description, type: string }
      - { name: image, label: Image, type: image }
      - { name: category, label: Category, type: string }
